import { Login } from "@/components";
import type { NextPage } from "next";
import Head from "next/head";
import {  LoginFormikProvider } from "providers";

const From: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex flex-col items-center gap-2">
        <LoginFormikProvider>
          <Login />
        </LoginFormikProvider>
      </section>
    </>
  );
};

export default From;
