export { Hero } from "./hero";
export { Card } from "./card";
export { Sick } from "./sick";
export { InfoUserForm } from "./InfoUserForm";
export { Login } from "./auth/loginCom";
export { Register } from "./auth/registerComp";
export { Choises } from "./choises";
export * from "./icons";
export { Sidebar } from "./sidebar";
export { Statistics } from "./Statistics";
export { SearchInput } from "./SearchInput";
export { CircleBar } from "./CircleBar";
export { ClientAuth } from "./ClientAuth";
