import { SearchInput } from "@/components";
import { Card, Sidebar, Statistics } from "@/components";
import { get, useAppSelector } from "@/hooks";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import styles from "../../styles/Home.module.css";
import {
  Arrowicon,
  CircleBar,
  Eyeicon,
  Filtericon,
  Navicon,
  Storeicon,
} from "@/components";

const Home: NextPage = () => {
  const router = useRouter();

  const admin = useAppSelector((state) => state.admin);
  const [users, setUsers] = useState<Array<any>>();
  const [vaccinated, setVaccinated] = useState();
  const [notVaccinated, setNotVaccinated] = useState();

  useEffect(() => {
    if (!admin.isLoggedIn) {
      router.push("/auth/login");
    }
  }, [admin]);

  useEffect(() => {
    const users = async () => {
      const all = await get("/user");
      setUsers(all);
      const vacc = all.filter((user: any) => user.vaccinations.length > 0);
      const notvac = all.filter((user: any) => user.vaccinations.length < 0);
      setVaccinated(vacc.length);
      setNotVaccinated(notvac.length);
    };
    users();
  }, []);

  if (!admin.isLoggedIn) return <div>checking your acceccebility... </div>;
  else
    return (
      <div className={styles.container} data-theme="fantasy">
        <Head>
          <title>Admin Dahsboard</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <section className="w-full h-screen flex font-poppins">
          <Sidebar />
          <div className="flex-1 overflow-y-scroll p-8 grid grid-cols-12 gap-6">
            <div className="col-span-12">
              <div className="col-span-2 bg-[#f9f8f3] p-8 rounded-3xl grid grid-cols-3 w-full">
                <div className="space-y-4 flex flex-col justify-center items-center">
                  <div className="bg-[#e4e0d5] w-12 h-12 text-black rounded-full grid place-content-center">
                    <Eyeicon />
                  </div>
                  <p className="text-[#8c8c8b] text-sm font-light">
                    vaccinated
                  </p>
                  <p className="text-black font-bold text-xl">{vaccinated}</p>
                </div>
                <div className="space-y-4 flex flex-col justify-center items-center">
                  <div className="bg-[#e4e0d5] w-12 h-12 text-black rounded-full grid place-content-center">
                    <Navicon />
                  </div>
                  <p className="text-[#8c8c8b] text-sm font-light">Users</p>
                  <p className="text-black font-bold text-xl">
                    {users?.length}
                  </p>
                </div>
                <div className="space-y-4 flex flex-col justify-center items-center">
                  <div className="bg-[#e4e0d5] w-12 h-12 text-black rounded-full grid place-content-center">
                    <Storeicon />
                  </div>
                  <p className="text-[#8c8c8b] text-sm font-light">Centers</p>
                  <p className="text-black font-bold text-xl">
                    {admin.info.centers?.length}
                  </p>
                </div>
              </div>
              <div className="grid grid-cols-2 gap-6 mt-20 ">
                <div className="bg-[#eefcef] p-8 rounded-3xl relative grid grid-cols-2 gap-4 items-center">
                  <div className="text-[#7bcd80] absolute top-0 right-0 p-5 rotate-45">
                    <Arrowicon />
                  </div>
                  <div>
                    <h3 className="font-bold text-black text-2xl mb-1">
                      vaccinated
                    </h3>
                    <p className="text-[#8c8c8b] text-sm mb-3">
                      at lease 1 shot
                    </p>
                    <p className="font-bold text-black text-3xl mb-1">
                      {vaccinated}
                    </p>
                  </div>
                  <div>
                    <CircleBar
                      percent={
                        vaccinated && users
                          ? Math.floor((vaccinated / users?.length) * 100)
                          : 30
                      }
                    />
                  </div>
                </div>

                <div className="bg-[#f4f5f9] p-8 rounded-3xl relative grid grid-cols-2 gap-4 items-center">
                  <div className="text-black absolute top-0 right-0 p-5 -rotate-45">
                    <Arrowicon />
                  </div>
                  <div>
                    <h3 className="font-bold text-black text-2xl mb-1">
                      not vaccinated
                    </h3>
                    <p className="text-[#8c8c8b] text-sm mb-3">
                      at more 1 shot
                    </p>
                    <p className="font-bold text-black text-3xl mb-1">400</p>
                  </div>
                  <div>
                    <CircleBar
                      percent={
                        notVaccinated && users
                          ? Math.floor((notVaccinated / users?.length) * 100)
                          : 0
                      }
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    );
};

export default Home;
