import {
  Arrowicon,
  CircleBar,
  Eyeicon,
  Filtericon,
  Navicon,
  Storeicon,
} from "@/components";
import { SearchInput } from "@/components";
import { Card, Sidebar, Statistics } from "@/components";
import { useAppSelector } from "@/hooks";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const router = useRouter();
  const admin = useAppSelector((state) => state.admin);
  useEffect(() => {
    if (!admin.isLoggedIn) {
      router.push("/auth/login");
    }


  }, [admin]);

  if (!admin.isLoggedIn) return <div>checking your acceccebility... </div>;
  else
    return (
      <div className={styles.container} data-theme="fantasy">
        <Head>
          <title>Admin Dahsboard</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <section className="w-full h-screen flex font-poppins">
          <Sidebar />
          <div className="flex-1 overflow-y-scroll p-8 grid grid-cols-12 gap-6">
            <div className="col-span-12">
              <SearchInput />
              <div className="flex items-center justify-between my-8">
                <div>
                  <h1 className="text-black font-bold text-3xl mb-1">
                    {admin.info.name}
                  </h1>
                  <p className="text-sm text-gray-400">Welcome Back!</p>
                </div>

                <button className="flex items-center px-4 py-2 border-2 space-x-3 border-gray-200 rounded-xl text-gray-400">
                  <span>Filters</span>
                  <Filtericon />
                </button>
              </div>
              <div className="grid grid-cols-2 gap-6">
                <div className="col-span-2 bg-[#f9f8f3] p-8 rounded-3xl grid grid-cols-3">
                  <div className="space-y-4">
                    <div className="bg-[#e4e0d5] w-12 h-12 text-black rounded-full grid place-content-center">
                      <Eyeicon />
                    </div>
                    <p className="text-[#8c8c8b] text-sm font-light">Views</p>
                    <p className="text-black font-bold text-xl">500</p>
                    <p className="text-[#8c8c8b] text-sm font-light">Per Day</p>
                  </div>
                  <div className="space-y-4">
                    <div className="bg-[#e4e0d5] w-12 h-12 text-black rounded-full grid place-content-center">
                      <Navicon />
                    </div>
                    <p className="text-[#8c8c8b] text-sm font-light">Visits</p>
                    <p className="text-black font-bold text-xl">200</p>
                    <p className="text-[#8c8c8b] text-sm font-light">
                      Per Minutes
                    </p>
                  </div>
                  <div className="space-y-4">
                    <div className="bg-[#e4e0d5] w-12 h-12 text-black rounded-full grid place-content-center">
                      <Storeicon />
                    </div>
                    <p className="text-[#8c8c8b] text-sm font-light">Orders</p>
                    <p className="text-black font-bold text-xl">5100</p>
                    <p className="text-[#8c8c8b] text-sm font-light">Per Day</p>
                  </div>
                </div>
                <div className="bg-[#ffeee2] p-8 rounded-3xl relative grid grid-cols-2 gap-4 items-center">
                  <div className="text-[#d58047] absolute top-0 right-0 p-5 rotate-45">
                    <Arrowicon />
                  </div>
                  <div>
                    <h3 className="font-bold text-black text-2xl mb-1">
                      Sales
                    </h3>
                    <p className="text-[#8c8c8b] text-sm mb-3">
                      Total Sales Today
                    </p>
                    <p className="font-bold text-black text-3xl mb-1">$500</p>
                  </div>
                  <div>
                    <CircleBar percent={55} />
                  </div>
                </div>
                <div className="bg-[#eefcef] p-8 rounded-3xl relative grid grid-cols-2 gap-4 items-center">
                  <div className="text-[#7bcd80] absolute top-0 right-0 p-5 rotate-45">
                    <Arrowicon />
                  </div>
                  <div>
                    <h3 className="font-bold text-black text-2xl mb-1">
                      Profit
                    </h3>
                    <p className="text-[#8c8c8b] text-sm mb-3">
                      Per day ration
                    </p>
                    <p className="font-bold text-black text-3xl mb-1">$150</p>
                  </div>
                  <div>
                    <CircleBar percent={30} />
                  </div>
                </div>
                <div className="bg-[#e6f5fa] p-8 rounded-3xl relative grid grid-cols-2 gap-4 items-center">
                  <div className="text-[#74c2d9] absolute top-0 right-0 p-5 -rotate-45">
                    <Arrowicon />
                  </div>
                  <div>
                    <h3 className="font-bold text-black text-2xl mb-1">
                      Orders
                    </h3>
                    <p className="text-[#8c8c8b] text-sm mb-3">
                      Total Order Today
                    </p>
                    <p className="font-bold text-black text-3xl mb-1">1000</p>
                  </div>
                  <div>
                    <CircleBar percent={80} />
                  </div>
                </div>
                <div className="bg-[#f4f5f9] p-8 rounded-3xl relative grid grid-cols-2 gap-4 items-center">
                  <div className="text-black absolute top-0 right-0 p-5 -rotate-45">
                    <Arrowicon />
                  </div>
                  <div>
                    <h3 className="font-bold text-black text-2xl mb-1">
                      Visits
                    </h3>
                    <p className="text-[#8c8c8b] text-sm mb-3">
                      Total Visit Today
                    </p>
                    <p className="font-bold text-black text-3xl mb-1">400</p>
                  </div>
                  <div>
                    <CircleBar percent={55} />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    );
};

export default Home;
